media: media
content:
  - name: chapitres
    label: Chapitres
    type: collection
    path: '_chapitres'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
        default: true
      - name: title
        label: Title
        type: string
      - name : image
        label : Image
        type : image
      - name : cours
        label : CoursPDF
        type : image
        options :
          path: media/chapitres
  - name: colles
    label: Colles
    type: collection
    path: '_colles'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
        default: true
      - name: title
        label: Title
        type: string
      - name : image
        label : Image
        type : image
      - name : cours
        label : CoursPDF
        type : image
        options :
          path: media/colles
  