media: public
content:
  - name: chapitres
    label: Chapitres
    type: collection
    path: "content/chapitres"
    view:
      fields: [name, published]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: name
        label: Titre
        type: string
      - name: image
        label: Image
        type: image
      - name: cours
        label: CoursPDF
        type: file
        options:
          path: media/chapitres
      - name: TD
        label: TD-PDF
        type: file
        options:
          path: media/chapitres
      - name: TDcor
        label: TD correction
        type: file
        options:
          path: media/chapitres
      - name: Autre
        label: Autre
        type: file
        options:
          path: media/chapitres
      - name: AutreLabel
        label: Autre label
        type: string
  - name: colles
    label: Colles
    type: collection
    path: "content/colles"
    view:
      fields: [titre, keywords, published, publishing_date, date]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: publishing_date
        label: Date de publication
        type: date
      - name: date
        label: Date
        type: date
        default: true
      - name: keywords
        label: Theme
        type: string
      - name: titre
        label: Semaine
        type: string
      - name: sujet
        label: Programme
        type: file
        options:
          path: media/
  - name: informatique
    label: informatique
    type: collection
    path: "content/informatique"
    view:
      fields: [titre, keywords, published, date]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: titre
        label: titre
        type: string
      - name: keywords
        label: Theme
        type: string
      - name: sujet
        label: pdf
        type: file
        options:
          path: media/
      - name: correction
        label: pdf
        type: file
        options:
          path: media/
  - name: devoirs
    label: Devoirs
    type: collection
    path: "content/devoirs"
    view:
      fields: [titre, type, published, date]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
        default: true
      - name: type
        label: type
        type: select
        options:
          values: [interro, DS, DM]
      - name: titre
        label: Titre
        type: string
      - name: keywords
        label: keyworsds (separé par des ;)
        type: string
      - name: sujet
        label: sujet
        type: file
        options:
          path: media/
      - name: dateSujet
        label: Publication du sujet
        type: date
      - name: correction
        label: Correction
        type: file
        options:
          path: media/
      - name: dateCorrection
        label: Publication de la correction
        type: date
      - name: notes
        label: Notes
        type: file
        options:
          path: media/
      - name: dateNote
        label: Publication des notes
        type: date
