media: public
content:
  - name: chapitres
    label: Chapitres
    type: collection
    path: '_chapitres'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
        default: true
      - name: titre
        label: Titre
        type: string
      - name : image
        label : Image
        type : image
      - name : cours
        label : CoursPDF
        type : image
        options :
          path: media/chapitres
      - name : TD
        label : TD-PDF
        type : image
        options :
          path: media/chapitres
      - name : TDcor
        label : TD correction
        type : image
        options :
          path: media/chapitres
  - name: colles
    label: Colles
    type: collection
    path: 'content/colles'
    view:
      fields: [ titre, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
        default: true
      - name: theme
        label: Theme
        type: string
      - name: titre
        label: Semaine
        type: string
      - name : programme
        label : Programme
        type : image
        options :
          path: media/colles
  - name: devoirs
    label: Devoirs
    type: collection
    path: '_devoirs'
    view:
      fields: [titre,type,  published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
        default: true
      - name: type
        label: type
        type: select
        options:
          values: [ Interro, DS]
      - name: titre
        label: Titre
        type: string
      - name : sujet
        label : sujet
        type : image
        options :
          path: media/
      - name: dateSujet
        label: Publication du sujet
        type: date
      - name : correction
        label : Correction
        type : image
        options :
          path: media/
      - name: dateCorrection
        label: Publication de la correction
        type: date
      - name : notes
        label : Notes
        type : image
        options :
          path: media/
      - name: dateNotes
        label: Publication des notes
        type: date

  